### ISSUE TITLE
Push to heroku fails when repository already exists

### ISSUE THREAD

**Issue by OleMussmann** [bitrise-steplib/steps-heroku-deploy#1]
Push to heroku fails when repository already exists. First push is fine, though. A solution could be to remove the existing repo first, or to merge?

```
set git remote heroku to https://git.heroku.com/XYZ.git
To https://git.heroku.com/XYZ.git
 ! [rejected]        HEAD -> master (fetch first)
error: failed to push some refs to 'https://git.heroku.com/XYZ.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
 [!] Failed to git push to heroku
```

**Comment by godrei** [comment]
Hi @OleMussmann ,
thanks for the issue report! We will have a look ASAP.

**Comment by OleMussmann** [comment]
Probably you would need to change
`git push heroku HEAD:master`
to 
`git push heroku HEAD:master --force`

I don't know how to test it locally, since I can't edit it in the bitrise repo.

**Comment by OleMussmann** [comment]
Fixed in pull request https://github.com/bitrise-steplib/steps-heroku-deploy/pull/2.

**Comment by viktorbenei** [comment]
Hi @OleMussmann , 

Just left some comment at https://github.com/bitrise-steplib/steps-heroku-deploy/pull/2

In general I'm OK with an **opt-in** force option, definitely don't do it by default.

> Push to heroku fails when repository already exists.

The issue is related to something else, this step definitely works if the repo already exists. We use it in production to publish various bitrise.io services ;)

The error simply states that you tried to push from a branch which is behind or not consistent with the one on heroku. This might happen if you e.g. try to push your e.g. `feature/a` branch which might conflict with a previous push from e.g. `feature/b`. But if you push the same branch every time it definitely works - e.g. we usually use this step only in case of a push to `master` or `develop` branch.

**Comment by trapacska** [comment]
Thanks @OleMussmann and also for the PR.

The new input is now released in the new version fo the step!
