### ISSUE TITLE
git-push-heroku-master

### ISSUE THREAD

**Issue by llsonkimm** [bitrise-steplib/steps-heroku-deploy#6]
i have a local git repository that i have associated with Heroku. Now am trying to deploy my code to heroku but i get the error -error: failed to push some refs to 'https://git.heroku.com/enigmatic-badlands-76250.git'. Kindly assist i am still new on Heroku.
![Capture error](https://user-images.githubusercontent.com/47587080/71726655-d720de80-2e48-11ea-81a9-ccfedebcdc05.JPG)

**Comment by istx25** [comment]
Hi @llsonkimm,

Thank you for reaching out.

If I understand you correctly - Bitrise has not been introduced to the project yet, and you are currently experiencing this problem on your local machine between the Git CLI tool and Heroku? If so, I would recommend reaching out to [Heroku's support for further assistance](https://www.heroku.com/support) as this repository is for the Bitrise continuous integration Step. If I am incorrect and misunderstood you, please clarify your question.

With that said, I can offer some suggestions for you to try:

This error can occur for one of many reasons but I'm going to focus on just two for right now: (1) Your origin repo is out of sync with your local repo or (2) The branch is protected or otherwise has custom settings that your push does not comply with.

For (1), try doing `git pull`, fix the merge conflict if there is one, and then run `git push` again.

For (2), the actual specifics of why this is happen can very a lot. I would recommend in this case to reach out to Heroku's support or post a topic on their forums and a community member over there can assist you. 

Please don't hesitate to follow-up if you have any other questions relating to Bitrise.

Kind regards,
Luna

**Comment by llsonkimm** [comment]
> 
> 
> Hi @llsonkimm,
> 
> Thank you for reaching out.
> 
> If I understand you correctly - Bitrise has not been introduced to the project yet, and you are currently experiencing this problem on your local machine between the Git CLI tool and Heroku? If so, I would recommend reaching out to [Heroku's support for further assistance](https://www.heroku.com/support) as this repository is for the Bitrise continuous integration Step. If I am incorrect and misunderstood you, please clarify your question.
> 
> With that said, I can offer some suggestions for you to try:
> 
> This error can occur for one of many reasons but I'm going to focus on just two for right now: (1) Your origin repo is out of sync with your local repo or (2) The branch is protected or otherwise has custom settings that your push does not comply with.
> 
> For (1), try doing `git pull`, fix the merge conflict if there is one, and then run `git push` again.
> 
> For (2), the actual specifics of why this is happen can very a lot. I would recommend in this case to reach out to Heroku's support or post a topic on their forums and a community member over there can assist you.
> 
> Please don't hesitate to follow-up if you have any other questions relating to Bitrise.
> 
> Kind regards,
> Luna

**Comment by llsonkimm** [comment]
Hi @non-binary 
Thank you for your response. I have read your suggestion and the idea that my branch is protected is the correct view of what i have experienced, and am working to resolve now. 
Thank you for your feed.

Regards,
Nelson

**Comment by istx25** [comment]
Hi @llsonkimm,

Sounds good!

We're here to help if you have any other Bitrise-related questions.

Have a good rest of your weekend!

Cheers,
Luna

**Comment by llsonkimm** [comment]
Hi Luna,
Kindly advice. I have just bumped into another issue on Heroku. I have this
GitHub repository that i have linked to my Heroku app, but on deploying, i
get an error of "

  No default language could be detected for this app."

It is a python app and when i run locally on my machine, it is
working. Kindly assist because it is a project i need to submit so
that i can secure a job somewhere.

Thank you.

Regards,

Nelson.

[image: image.png]

**Comment by istx25** [comment]
Hi @llsonkimm,

As previously mentioned, this repository is related to the product Bitrise (https://bitrise.io) not Heroku (https://heroku.com).

Please reach out to Heroku support to receive additional assistance:

https://stackoverflow.com/questions/tagged/heroku
https://help.heroku.com/

Cheers,
Luna
